name: do_an_2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.1.0
  flutter_screenutil: ^5.9.0
  percent_indicator: ^4.2.3
  google_fonts: 6.1.0
  google_sign_in: ^5.2.1
  http: ^1.2.0
  simple_circular_progress_bar: ^1.0.2
  simple_animation_progress_bar: ^1.6.0
  fl_chart: ^0.62.0
  dropdown_button2: ^2.3.9
  uuid: ^4.4.0
  image_picker: ^1.0.8
  video_player: ^2.8.6
  video_editor: ^3.0.0
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  flutter_quill: ^9.3.7
  cloudinary_sdk: ^5.0.0+1
  date_picker_timeline: ^1.2.5
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/PublicSans-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
