# Config server
server:
  port: 8088

spring:
  # config to use .env file
  config:
    import: optional:file:.env[.properties]
  # config database mongodb
  data:
    mongodb:
      database: ${MONGO_DATABSE}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
  sendgrid:
    api-key: ${API_KEY_SEND_GRID}

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=